import { StyleSheet } from "@react-pdf/renderer";

export const labSetupComponentPageStyles = StyleSheet.create({
  page: {
    padding: 0,
    backgroundColor: "#FFFFFF",
    fontFamily: "Helvetica",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    position: "relative",
  },
  redSidebar: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: "10%",
    backgroundColor: "#FF3131",
    zIndex: -1,
  },
  mainContent: {
    marginLeft: "16%",
    marginRight: "6%",
    marginTop: 40,
    marginBottom: 40,
    display: "flex",
    flexDirection: "column",
    gap: 15,
  },
  photo: {
    width: "100%",
    height: "100%",
    borderRadius: 6,
    objectFit: "cover",
  },
  infoBlockContainer: {
    position: "relative",
    marginTop: 20,
  },
  blockHeaderContainer: {
    backgroundColor: "#FF3131",
    paddingVertical: 8,
    paddingHorizontal: 20,
    alignSelf: "flex-start",
    position: "absolute",
    top: -8,
    left: 20,
    zIndex: 0,
  },
  blockHeaderText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "heavy",
  },
  yellowContentBox: {
    backgroundColor: "#F4CE14",
    paddingTop: 40,
    paddingBottom: 20,
    paddingHorizontal: 25,
    zIndex: 0,
    position: "relative",
  },
  row: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  halfImage: {
    width: "48%",
    height: 150,
    borderRadius: 8,
    overflow: "hidden",
  },
  halfContent: {
    width: "48%",
    display: "flex",
    flexDirection: "column",
  },
  introText: {
    fontSize: 12,
    lineHeight: 1.4,
    textAlign: "justify",
    color: "#1A1A1B",
  },
  paragraph: {
    fontSize: 13,
    lineHeight: 1.2,
    textAlign: "justify",
    color: "#1A1A1B",
  },
  middleWidePhoto: {
    width: "100%",
    height: 220,
    borderRadius: 12,
    objectFit: "cover",
    marginVertical: 15,
  },
});
